#!/bin/bash

# This is an autogenerated script for Torque PBS

#PBS -S /bin/bash
#PBS -N GATKcoverage
#PBS -e log/GATKcoverage.err
#PBS -o log/GATKcoverage.out
#PBS -V
#PBS -l vmem=8g
#PBS -l mem=8g
#PBS -l walltime=48:00:00

export TMPDIR=/localhd/${PBS_JOBID}

module load samtools/1.9 gatk/2.8.1

# change to the working directory
working_dir=$(dirname $bam)
cd $working_dir

output=${working_dir}/$(basename $bam .bam).gatk.depthofcoverage

/hpf/tools/centos6/java/1.7.0/bin/java -Xmx4g -jar /hpf/tools/centos6/gatk/2.8.1/GenomeAnalysisTK.jar -T DepthOfCoverage -o ${output} -I ${bam} -R /hpf/largeprojects/adam/local/reference/homosapiens/ucsc/hs37d5/bwa/hs37d5.fa --omitDepthOutputAtEachBase -L /hpf/largeprojects/adam/local/genomes/homosapiens/gatk/2.8.1/intervals/hs37d5.intervals

echo EXIT STATUS $?

echo Job ${PBS_JOBID} -- ${PBS_JOBNAME} Complete!
